version: '3.8'

services:
  rag-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rag-classifier
    container_name: rag-classifier
    ports:
      - "8501:8501"
    volumes:
      - ./data:/data
      - rag_data:/app/data
    command: app
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0

  generator:
    image: rag-classifier
    volumes:
      - ./data:/data
    command: generate --samples=200 --output=/data/generated_dataset.csv
    profiles:
      - generator

volumes:
  rag_data: